"""Word-risk XGBoost pipeline for ScribeShield."""

from .features import (
    ARTIFACTS_DIR,
    DATA_DIR,
    DEFAULT_DATASET_PATH,
    DEFAULT_RETRAINING_SNAPSHOTS_PATH,
    DEFAULT_TRAINING_HISTORY_PATH,
    DEFAULT_XGB_MODEL_PATH,
    REPORTS_DIR,
)

__all__ = [
    "ARTIFACTS_DIR",
    "DATA_DIR",
    "DEFAULT_DATASET_PATH",
    "DEFAULT_RETRAINING_SNAPSHOTS_PATH",
    "DEFAULT_TRAINING_HISTORY_PATH",
    "DEFAULT_XGB_MODEL_PATH",
    "REPORTS_DIR",
]
